### ISSUE TITLE
Paragraph symbol inserted in TOC when building to PDF

### ISSUE THREAD

**Issue by NickCrews** [danielfrg/mkdocs-jupyter#153]
I'm not sure what level of the stack this bug is coming from, please direct me to the right place if this isn't the right place.

If I render a notebook with the following first cell of markdown:

```markdown
# Types and Schemas

It's important to understand the types of data that we're working with.
We use a lot of SQL tables, and it's important to understand the schema
of these tables.
```

and then render to a PDF using the `with-pdf` plugin, then the link in the TOC has a weird "next-paragraph" symbol (the other pages are from .md files and appear fine):

<img width="845" alt="image" src="https://github.com/danielfrg/mkdocs-jupyter/assets/10820686/8ac26a8d-25a1-4f04-88c3-3aff01904947">

The rendered HTML of the navbar looks just fine though : `<a href="reference/types.html" class="md-nav__link">
        Types and Schemas
      </a>`

Perhaps this is an issue with the `with-pdf` plugin? This is the config that I am using:

```yaml
site_name: my_site
theme:
  name: material
plugins:
  - search
  - literate-nav
  - offline
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
      show_input: false
  - with-pdf:
      author: Nick Crews
      enabled_if_env: ENABLE_PDF_EXPORT
```

Thank you for your help!
