### ISSUE TITLE
Equations intermittently not rendering on Safari

### ISSUE THREAD

**Issue by hannorein** [danielfrg/mkdocs-jupyter#156]
I'm having an issue with LaTeX equations sometimes (actually, most of the time) not render in my notebooks. As an example, see this [this notebook](https://rebound.readthedocs.io/en/latest/ipython_examples/IntegratingArbitraryODEs/). I only encounter this on Safari. Chrome and Firefox seem fine. I'm having a hard time making sense of it. Maybe this is some sort of race condition? When the equations don't render, I get errors in the console:

```
[Error] TypeError: undefined is not an object (evaluating 'MathJax.Ajax.Preloading')
	Global Code (TeX-AMS_CHTML-full.js:15)
[Error] TypeError: undefined is not an object (evaluating 'MathJax.Hub.Startup')
	(anonymous function) (MathJax.js:19:50139)
	execute (MathJax.js:19:3248)
	cb (MathJax.js:19:2825)
```

**Comment by emoshou** [comment]
I'm having the same issue.

Equations render correctly in Safari when running mkdocs locally, but do not render when hosted on a Github pages. The equations render correctly in Chrome.

**Comment by Wikstahl** [comment]
Hi! Have you found a solution to this yet?

**Comment by Wikstahl** [comment]
I had to include this in order for equations to be rendered correctly.
```
- mkdocs-jupyter:
      execute: false
      include_requirejs: true
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"
```
