### ISSUE TITLE
xarray DataArray and Dataset HTML representation

### ISSUE THREAD

**Issue by blaylockbk** [danielfrg/mkdocs-jupyter#164]
Hi mkdocs-jupyter, Thanks for providing this support. It's been great to work with.

One thing I've run into is the Xarray DataArray and Dataset HTML representations are not rendered the same as they are in a Jupyter Notebook.

In Jupyter
```python
import xarray as xr
import numpy as np

data = xr.DataArray(np.random.randn(2, 3), dims=("x", "y"), coords={"x": [10, 20]})
data
```
<img width="455" alt="image" src="https://github.com/danielfrg/mkdocs-jupyter/assets/6249613/1e40cc98-d428-4dbc-95a4-97e59615e23d">

Rendered in MkDocs (light and dark theme in mkdocs material)

<img width="530" alt="image" src="https://github.com/danielfrg/mkdocs-jupyter/assets/6249613/d58324ed-a2c2-4e80-b91a-012883c9ef87">

<img width="529" alt="image" src="https://github.com/danielfrg/mkdocs-jupyter/assets/6249613/f8e9fda5-c266-4fd9-ba5b-62ed62722677">

Some of the elements are there, but it doesn't look quite right.

---
I was expecting it to render similar to how mkdocs-jupyter nicely handles a Pandas DataFrame

```python
import pandas as pd
pd.DataFrame({"A": [1, 2, 3, 4]})
```
<img width="515" alt="image" src="https://github.com/danielfrg/mkdocs-jupyter/assets/6249613/294e70d0-42d7-480b-8f39-fd267f96837d">

<img width="523" alt="image" src="https://github.com/danielfrg/mkdocs-jupyter/assets/6249613/02bd6f94-1c01-47e4-8bbb-40a26504ba0e">

Thanks for your consideration on this issue.

**Comment by danielfrg** [comment]
It should be a matter of adding some CSS styles. We do that for pandas so they look good.

**Comment by brynpickering** [comment]
Based on https://github.com/damianavila/RISE/issues/594, I added this to my CSS to at least remove the repetition of the dataset contents in pretty and simple HTML:

```css
.md-typeset pre.xr-text-repr-fallback {
    display: none;
}
```

Ideally the dropdowns would all be closed by default but it seems that it only closes them when there are >=10 items in the dropdown.

**Comment by brynpickering** [comment]
I've gone into the CSS and made more tweaks that now lead to what I _think_ is the correct formatting for the xarray dataset HTML representation:

```css
.md-typeset pre.xr-text-repr-fallback {
    display: none;
}

.md-typeset ul.xr-sections, .jupyter-wrapper .jp-OutputArea-output dl.xr-attrs {
    display: grid;
}

.md-typeset li.xr-var-item, .md-typeset ul.xr-var-list {
    display: contents;
}

.md-typeset .xr-section-details {
    display: none;
}

.md-typeset ul.xr-dim-list li {
    margin-bottom: 0;
    margin-left: 0;
}

.md-typeset ul.xr-dim-list {
    margin-bottom: 0;
    margin-top: 0;
}

.jupyter-wrapper .jp-OutputArea-output .xr-attrs dt {
    padding: 0;
    margin: 0;
    float: left;
    padding-right: 10px;
    width: auto;
    font-weight: normal;
    grid-column: 1;
}
```
