### ISSUE TITLE
Add Support for Jinja2 Overrides

### ISSUE THREAD

**Issue by rarnold97** [danielfrg/mkdocs-jupyter#178]
Ideally, a user should be able to add in their own jinja file that can inherit from the jupyter lab  template used in `notebook.html.j2`  The use case in my application was I wanted to be able to make cell outputs collapsable, and remove execution counts from the rendered cells.  It is currently impossible to do so without forking or just making my own nbconvert plugin.

Example config:

```yaml
plugins:
  - mkdocs-jupyter
      custom_overrides:
        my_jupyter_overrides/
```
