### ISSUE TITLE
Navigation panel always uses h1 title

### ISSUE THREAD

**Issue by mwermelinger** [danielfrg/mkdocs-jupyter#189]
My mkdocs.yml file includes something like:
```yaml
nav:
  - Introduction:
    - Home: index.md
    - Examples and Templates: example-essays.md
    - getting-started.md
  - Templates:
    - Intro Prog: examples/template-intro-programming.ipynb
    - DSA: examples/template-data-structures.ipynb
```
The navigation panel shows the defined titles (Home, etc.) for the Markdown files, but for the notebooks it uses the H1 headers in the notebooks and ignores 'Intro Prog' and 'DSA'. Is this a feature or a bug? The example in the README seems to imply that one can override the H1 headers.

I'm using mkdocs 1.5.3 and mkdocs-jupyter 0.24.6. I've commented out everything in mkdocs.yml except the navigation, to make sure it wasn't a conflict with other plugins and markdown extensions I use. Thanks in advance for any help and clarifications.
