### ISSUE TITLE
Math doesn't render due to empty script tag in 0.24.8

### ISSUE THREAD

**Issue by econandrew** [danielfrg/mkdocs-jupyter#212]
Under 0.24.7 I get HTML source with:

```html
<!-- Load mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"></script>
<!-- MathJax configuration -->
<script type="text/x-mathjax-config">
```

under 0.24.8 I get:

```html
<!-- Load mathjax -->
<script src=""></script>
<!-- MathJax configuration -->
<script type="text/x-mathjax-config">
```

I assume something is interacting with the custom mathjax change in 0.24.8. For now I'm freezing at 0.24.7 but I'm happy help figure out what's going on here if you can suggest how to proceed.

---

`mkdocs.yml` plugins section shows:

```yaml
plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - deployments/*
        - deployments_by_name/*
  - mkdocs-jupyter:
      include_source: true
      ignore: ["docs/runbooks/laptop_setup/test_jupyter_di.ipynb"]
  - macros:
      render_by_default: false
  - git-authors:
      show_email_address: false
      exclude:
        - deployments/*
        - deployments_by_name/*
```

`pip freeze` gives the same with both versions (apart from the mkdocs-jupyter version itself:

```
appnope==0.1.4
asttokens==2.4.1
attrs==23.2.0
Babel==2.15.0
beautifulsoup4==4.12.3
bleach==6.1.0
bracex==2.4
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.2.2
debugpy==1.8.2
decorator==5.1.1
defusedxml==0.7.1
executing==2.0.1
fastjsonschema==2.20.0
ghp-import==2.1.0
gitdb==4.0.11
GitPython==3.1.43
idna==3.7
ipykernel==6.29.5
ipython==8.26.0
jedi==0.19.1
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyterlab_pygments==0.3.0
jupytext==1.16.3
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mdit-py-plugins==0.4.1
mdurl==0.1.2
mergedeep==1.3.4
mistune==3.0.2
mkdocs==1.6.0
mkdocs-awesome-pages-plugin==2.9.3
mkdocs-get-deps==0.2.0
mkdocs-git-authors-plugin==0.9.0
mkdocs-git-revision-date-localized-plugin==1.2.6
mkdocs-jupyter==0.24.7
mkdocs-macros-plugin==1.0.5
mkdocs-material==9.5.30
mkdocs-material-extensions==1.3.1
natsort==8.4.0
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
packaging==24.1
paginate==0.5.6
pandocfilters==1.5.1
parso==0.8.4
pathspec==0.12.1
pexpect==4.9.0
platformdirs==4.2.2
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
Pygments==2.18.0
pymdown-extensions==10.8.1
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
pyyaml_env_tag==0.1
pyzmq==26.0.3
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rpds-py==0.19.1
six==1.16.0
smmap==5.0.1
soupsieve==2.5
stack-data==0.6.3
termcolor==2.4.0
tinycss2==1.3.0
tornado==6.4.1
traitlets==5.14.3
typing_extensions==4.12.2
urllib3==2.2.2
watchdog==4.0.1
wcmatch==8.5.2
wcwidth==0.2.13
webencodings==0.5.1
```
