### ISSUE TITLE
feature: hide output by tag

### ISSUE THREAD

**Issue by cmatKhan** [danielfrg/mkdocs-jupyter#221]
This is related to #181, which itself has some links to other issues.

I am wondering if it is possible to hide output in a similar fashion to this:

```
plugins:
    - mkdocs-jupyter:
          remove_tag_config:
              remove_input_tags:
                  - hide_code
              remove_output_tags:
                  - hide_output
```

If not, that would be a nice feature.
