### ISSUE TITLE
Scrollable output cells

### ISSUE THREAD

**Issue by dstansby** [danielfrg/mkdocs-jupyter#232]
For long output cells (over a certain line length I guess), it would be super neat if these could become scrollable boxes to avoid them taking up too much room on a page.

**Comment by JoshuaSiraj** [comment]
### Work around to do this:

#### Make a docs/assets/styles.css with:

```css
/* Make Jupyter notebook output cells scrollable */
.jp-Cell-outputWrapper  {
    max-height: 450px; /* Adjust height as needed */
    overflow-y: auto;
    padding: 10px;
    border-radius: 5px;
}
```

#### Update mkdocs.yml
```yaml
extra_css:
  - assets/styles.css
```

**Comment by dstansby** [comment]
Thanks! Do you know if there's a way to make add a horizontal scroll bar if text is too long?

**Comment by JoshuaSiraj** [comment]
Np. I've tried and can't seem to get that to work.

**Comment by thomasmarwitz** [comment]
@dstansby 

Try this: 

```yaml
plugins:
  - search
  - mkdocs-jupyter:
      highlight_extra_classes: jupyter-custom-highlight
```

Custom css that you add through mkdocs
```css
.jupyter-custom-highlight .jp-OutputArea-area > pre {
    white-space: pre;
}
```
