### ISSUE TITLE
Support for nested pages

### ISSUE THREAD

**Issue by tiefenthaler** [danielfrg/mkdocs-jupyter#235]
Mkdocs-jupyter does not support nested pages to be configured in the mkdocs.yml like:

```yml
nav:
  - Home: index.md
  - Source Code API Reference:
      - Autoencoder: api/autoencoder.md
      - Training: api/training.md
      - FastAPI: api/fastapi_app.md
  # NOTE: Does not support nested lists.
  - Notebooks 
    - Main: main.ipynb
    - Demo: demo.ipynb
```

Only supports not nested structure:
```yml
nav:
  - Home: index.md
  - Source Code API Reference:
      - Autoencoder: api/autoencoder.md
      - Training: api/training.md
      - FastAPI: api/fastapi_app.md
  # NOTE: Does not support nested lists.
  - Notebooks - Main: main.ipynb
  - Notebooks - Demo: demo.ipynb
```
