### ISSUE TITLE
Download button missing

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#24]
How to enable the download button? Here is my [mkdocs.yml.](https://github.com/giswqs/geemap/blob/master/mkdocs.yml#L24) I looked at other websites with the download button, I could not find settings to enable the download button except the following lines. Thanks. 

```
plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
```

https://geemap.org/notebooks/01_geemap_intro/
![](https://i.imgur.com/vVeOA2R.png)

https://developmentseed.org/titiler/examples/Working_with_CloudOptimizedGeoTIFF_simple/
![](https://i.imgur.com/EClNazj.png)
