### ISSUE TITLE
Strip out the `In` and `Out` label for code cells

### ISSUE THREAD

**Issue by hadim** [danielfrg/mkdocs-jupyter#30]
The css class is `jp-InputPrompt jp-InputArea-prompt`. Tweaking the CSS to add `visiblity: hidden`  to it make it disappear but leave an empty block.

Is there is another way to strip out this HTML block?

**Comment by danielfrg** [comment]
Right now the only way to do that is changing the CSS as you suggest.

I personally like them but at one point we could make this optional.

**Comment by hadim** [comment]
Actualy `display: none` should do the job. Will try soon.

**Comment by hadim** [comment]
I confirm `display: none` works.

```css
/* Remove the `In` and `Out` block in rendered Jupyter notebooks */
.md-container .jp-Cell-outputWrapper .jp-OutputPrompt.jp-OutputArea-prompt,
.md-container .jp-Cell-inputWrapper .jp-InputPrompt.jp-InputArea-prompt {
  display: none;
}
```
