### ISSUE TITLE
Copy Button Ignores Theme and Include Source Doesn't Work

### ISSUE THREAD

**Issue by andynameistaken** [danielfrg/mkdocs-jupyter#75]
## Config
```yaml
plugins:
  - mkdocs-jupyter:
      execute: True
      # theme: dark
      include_source: True

```

## With Light Theme

<img width="808" alt="image" src="https://user-images.githubusercontent.com/15692002/162750125-f87bd044-2276-4ee1-8277-283322d4d345.png">

## With Dark Theme
![image](https://user-images.githubusercontent.com/15692002/162751326-749d4079-90be-4079-ae92-1a4c8a1fdd1d.png)
